// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDejvJZv2sqlYXx1YKafG3x7U_y4pb_R5s',
//     appId: '1:22217432676:web:250ac9e28d4726217ac971',
//     messagingSenderId: '22217432676',
//     projectId: 'perfacto-7aa56',
//     authDomain: 'perfacto-7aa56.firebaseapp.com',
//     storageBucket: 'perfacto-7aa56.firebasestorage.app',
//     measurementId: 'G-2GX25C97VH',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAW9Nirr3OAJPuAv0cxKnVBAGRPyF9QWTE',
//     appId: '1:22217432676:android:d91f64a05ae859607ac971',
//     messagingSenderId: '22217432676',
//     projectId: 'perfacto-7aa56',
//     storageBucket: 'perfacto-7aa56.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAkL7o31Sz1QrCQZMhAmcWiRuqPM-L6LaI',
//     appId: '1:22217432676:ios:68e03d910962699c7ac971',
//     messagingSenderId: '22217432676',
//     projectId: 'perfacto-7aa56',
//     storageBucket: 'perfacto-7aa56.firebasestorage.app',
//     iosBundleId: 'com.example.perfacto',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAkL7o31Sz1QrCQZMhAmcWiRuqPM-L6LaI',
//     appId: '1:22217432676:ios:316ea74941846c327ac971',
//     messagingSenderId: '22217432676',
//     projectId: 'perfacto-7aa56',
//     storageBucket: 'perfacto-7aa56.firebasestorage.app',
//     iosBundleId: 'com.example.pohangMap',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDejvJZv2sqlYXx1YKafG3x7U_y4pb_R5s',
//     appId: '1:22217432676:web:2675a3443a1e072d7ac971',
//     messagingSenderId: '22217432676',
//     projectId: 'perfacto-7aa56',
//     authDomain: 'perfacto-7aa56.firebaseapp.com',
//     storageBucket: 'perfacto-7aa56.firebasestorage.app',
//     measurementId: 'G-WGS8CFNBGX',
//   );
// }
